baseurl      = "https://www.anvbis.net"
title        = "Anvbis"
languageCode = "en-au"
theme        = "terminal"
paginate     = 5

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = false

  # Subtitle for home
  homeSubtitle = "Exploit development and reverse engineering."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Exploit development and reverse engineering writeups."
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[permalinks]
    categories = "/:section/:slug"

[languages]
  [languages.en]
    languageName = "English"
    title = "Anvbis"
  # subtitle = "Aspiring exploit developer."
    keywords = ""
    copyright = 'Copyright 2020 Anvbis'
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    issingBackButtonLabel = "Return to home page"

    [languages.en.params.logo]
      logoText = "anvbis"
      logoHomeLink = "/"

  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "blog"
      name       = "Blog"
      url        = "/posts"
