baseurl = "https://anvbis.github.io/"
languageCode = "en-au"
theme = "risotto"
paginate = 5

[markup.highlight]
  noClasses = false

[params]
  noindex = false

[params.theme]
  palette = "horizon-dark"

[params.about]
  title = ""
  description = ""

[[params.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/anvbis"

[[params.socialLinks]]
  icon = "fa fa-envelope"
  title = "Email"
  url = "mailto:contact@anvbis.au"

[languages]
  [languages.en]
    title = "anvbis"

  [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
