baseurl = "https://anvbis.github.io/"
languageCode = "en-au"
theme = "terminal"
paginate = 5

[params]
  themeColor = "green"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  autoCover = true

[languages]
  [languages.en]
    title = "Anvbis"
    subtitle = "Exploit development and reverse engineering."
    keywords = ""
    copyright = "Anvbis"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Anvbis"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
