baseurl      = "https://anvbis.github.io"
title        = "Anubis"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "2006-01-02"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Aspiring exploit developer."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Exploit development and reverse engineering writeups."
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[permalinks]
    categories = "/:section/:slug"

[languages]
  [languages.en]
    title = "Anubis"
  # subtitle = "Aspiring exploit developer."
    keywords = ""
    copyright = 'Copyright 2020 Anvbis'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "anvbis"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/logo.jpg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
