baseurl = "https://anvbis.github.io/"
languageCode = "en-au"
theme = "risotto"
paginate = 5

[params]
  noindex = false

[params.theme]
  palette = "horizon-dark"

[params.about]
  title = "Anvbis"
  description = "Exploit development and reverse engineering."

[[params.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/anvbis"

[languages]
  [languages.en]
    title = "anvbis"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
